homepage:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
        route: admin
        permanent: true

controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute

api_auth_login:
    path: /api/auth/login
