services:
  db:
    image: postgres:18@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
    volumes:
      - burgieclan-db:/var/lib/postgresql/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: burgieclan_db_pass
      POSTGRES_DB: burgieclan_db
      POSTGRES_USER: burgieclan_db_user

volumes:
  burgieclan-db: {}
