services:
  db:
    image: postgres:18@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    volumes:
      - burgieclan-db:/var/lib/postgresql/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: burgieclan_db_pass
      POSTGRES_DB: burgieclan_db
      POSTGRES_USER: burgieclan_db_user

volumes:
  burgieclan-db: {}
