services:
  db:
    image: postgres:18@sha256:06cad38a5d9f5d24b4d83d86def30795d5e4b757fedbf5281172b576dedcd941
    volumes:
      - burgieclan-db:/var/lib/postgresql/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: burgieclan_db_pass
      POSTGRES_DB: burgieclan_db
      POSTGRES_USER: burgieclan_db_user

volumes:
  burgieclan-db: {}
