knpu_oauth2_client:
  clients:
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
    litus_backend:
      type: generic
      provider_class: App\OauthProvider\LitusProvider
      provider_options:
        urlAuthorize: "%env(LITUS_OAUTH_AUTHORIZE)%"
        urlAccessToken: "%env(LITUS_OAUTH_TOKEN)%"
        urlResourceOwnerDetails: "%env(LITUS_OAUTH_RESOURCE_OWNER_DETAILS)%"
      client_id: "%env(LITUS_API_KEY)%"
      client_secret: "%env(LITUS_SECRET)%"
      redirect_route: login_litus
      use_state: false # needed to allow login through kuleuven shibboleth

    # client for API/frontend login
    litus_api:
      type: generic
      provider_class: App\OauthProvider\LitusProvider
      provider_options:
        urlAuthorize: "%env(LITUS_OAUTH_AUTHORIZE)%"
        urlAccessToken: "%env(LITUS_OAUTH_TOKEN)%"
        urlResourceOwnerDetails: "%env(LITUS_OAUTH_RESOURCE_OWNER_DETAILS)%"
      client_id: "%env(LITUS_API_KEY)%"
      client_secret: "%env(LITUS_SECRET)%"
      redirect_route: api_oauth_callback
      use_state: false # needed to allow login through kuleuven shibboleth
