vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        document_object:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
