vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        document_object:
            uri_prefix: /files/download
            upload_destination: '%kernel.project_dir%/data/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
