vich_uploader:
    db_driver: orm
    storage: flysystem
    metadata:
        type: attribute
    mappings:
        document_object:
            uri_prefix: /files/download
            upload_destination: 'document.storage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
