/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiCoursesGetCollection200Response,
  Course,
  CourseJsonld,
} from '../models';
import {
    ApiCoursesGetCollection200ResponseFromJSON,
    ApiCoursesGetCollection200ResponseToJSON,
    CourseFromJSON,
    CourseToJSON,
    CourseJsonldFromJSON,
    CourseJsonldToJSON,
} from '../models';

export interface ApiCoursesGetCollectionRequest {
    page?: any;
    name?: any;
    code?: any;
}

export interface ApiCoursesIdGetRequest {
    id: any;
}

/**
 * 
 */
export class CourseApi extends runtime.BaseAPI {

    /**
     * Retrieves the collection of Course resources.
     * Retrieves the collection of Course resources.
     */
    async apiCoursesGetCollectionRaw(requestParameters: ApiCoursesGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiCoursesGetCollection200Response>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.code !== undefined) {
            queryParameters['code'] = requestParameters.code;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/courses`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiCoursesGetCollection200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the collection of Course resources.
     * Retrieves the collection of Course resources.
     */
    async apiCoursesGetCollection(requestParameters: ApiCoursesGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiCoursesGetCollection200Response> {
        const response = await this.apiCoursesGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a Course resource.
     * Retrieves a Course resource.
     */
    async apiCoursesIdGetRaw(requestParameters: ApiCoursesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseJsonld>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiCoursesIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/courses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseJsonldFromJSON(jsonValue));
    }

    /**
     * Retrieves a Course resource.
     * Retrieves a Course resource.
     */
    async apiCoursesIdGet(requestParameters: ApiCoursesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseJsonld> {
        const response = await this.apiCoursesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
