/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiDocumentCategoriesGetCollection200Response,
  DocumentCategory,
  DocumentCategoryJsonld,
} from '../models';
import {
    ApiDocumentCategoriesGetCollection200ResponseFromJSON,
    ApiDocumentCategoriesGetCollection200ResponseToJSON,
    DocumentCategoryFromJSON,
    DocumentCategoryToJSON,
    DocumentCategoryJsonldFromJSON,
    DocumentCategoryJsonldToJSON,
} from '../models';

export interface ApiDocumentCategoriesGetCollectionRequest {
    page?: any;
    name?: any;
}

export interface ApiDocumentCategoriesIdGetRequest {
    id: any;
}

/**
 * 
 */
export class DocumentCategoryApi extends runtime.BaseAPI {

    /**
     * Retrieves the collection of Document Category resources.
     * Retrieves the collection of Document Category resources.
     */
    async apiDocumentCategoriesGetCollectionRaw(requestParameters: ApiDocumentCategoriesGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDocumentCategoriesGetCollection200Response>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/document_categories`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiDocumentCategoriesGetCollection200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the collection of Document Category resources.
     * Retrieves the collection of Document Category resources.
     */
    async apiDocumentCategoriesGetCollection(requestParameters: ApiDocumentCategoriesGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDocumentCategoriesGetCollection200Response> {
        const response = await this.apiDocumentCategoriesGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a Document Category resource.
     * Retrieves a Document Category resource.
     */
    async apiDocumentCategoriesIdGetRaw(requestParameters: ApiDocumentCategoriesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentCategoryJsonld>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiDocumentCategoriesIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/document_categories/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentCategoryJsonldFromJSON(jsonValue));
    }

    /**
     * Retrieves a Document Category resource.
     * Retrieves a Document Category resource.
     */
    async apiDocumentCategoriesIdGet(requestParameters: ApiDocumentCategoriesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentCategoryJsonld> {
        const response = await this.apiDocumentCategoriesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
