/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LitusAuthentication,
  LitusAuthenticationJsonld,
} from '../models';
import {
    LitusAuthenticationFromJSON,
    LitusAuthenticationToJSON,
    LitusAuthenticationJsonldFromJSON,
    LitusAuthenticationJsonldToJSON,
} from '../models';

export interface LitusAuthenticationRequest {
    litusAuthenticationJsonld: LitusAuthenticationJsonld;
}

/**
 * 
 */
export class LitusAuthenticationApi extends runtime.BaseAPI {

    /**
     * Creates a Litus Authentication resource.
     * Creates a Litus Authentication resource.
     */
    async litusAuthenticationRaw(requestParameters: LitusAuthenticationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LitusAuthenticationJsonld>> {
        if (requestParameters.litusAuthenticationJsonld === null || requestParameters.litusAuthenticationJsonld === undefined) {
            throw new runtime.RequiredError('litusAuthenticationJsonld','Required parameter requestParameters.litusAuthenticationJsonld was null or undefined when calling litusAuthentication.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/ld+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auth/litus`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LitusAuthenticationJsonldToJSON(requestParameters.litusAuthenticationJsonld),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LitusAuthenticationJsonldFromJSON(jsonValue));
    }

    /**
     * Creates a Litus Authentication resource.
     * Creates a Litus Authentication resource.
     */
    async litusAuthentication(requestParameters: LitusAuthenticationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LitusAuthenticationJsonld> {
        const response = await this.litusAuthenticationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
