/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoginCheckPost200Response,
  LoginCheckPostRequest,
} from '../models';
import {
    LoginCheckPost200ResponseFromJSON,
    LoginCheckPost200ResponseToJSON,
    LoginCheckPostRequestFromJSON,
    LoginCheckPostRequestToJSON,
} from '../models';

export interface LoginCheckPostOperationRequest {
    loginCheckPostRequest: LoginCheckPostRequest;
}

/**
 * 
 */
export class LoginCheckApi extends runtime.BaseAPI {

    /**
     * Creates a user token.
     * Creates a user token.
     */
    async loginCheckPostRaw(requestParameters: LoginCheckPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginCheckPost200Response>> {
        if (requestParameters.loginCheckPostRequest === null || requestParameters.loginCheckPostRequest === undefined) {
            throw new runtime.RequiredError('loginCheckPostRequest','Required parameter requestParameters.loginCheckPostRequest was null or undefined when calling loginCheckPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginCheckPostRequestToJSON(requestParameters.loginCheckPostRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginCheckPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a user token.
     * Creates a user token.
     */
    async loginCheckPost(requestParameters: LoginCheckPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginCheckPost200Response> {
        const response = await this.loginCheckPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
