/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PageJsonld,
} from '../models';
import {
    PageJsonldFromJSON,
} from '../models';

export interface ApiPagesUrlKeyGetRequest {
    urlKey: any;
}

/**
 * 
 */
export class PageApi extends runtime.BaseAPI {

    /**
     * Retrieves a Page resource.
     * Retrieves a Page resource.
     */
    async apiPagesUrlKeyGetRaw(requestParameters: ApiPagesUrlKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageJsonld>> {
        if (requestParameters.urlKey === null || requestParameters.urlKey === undefined) {
            throw new runtime.RequiredError('urlKey','Required parameter requestParameters.urlKey was null or undefined when calling apiPagesUrlKeyGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/pages/{urlKey}`.replace(`{${"urlKey"}}`, encodeURIComponent(String(requestParameters.urlKey))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageJsonldFromJSON(jsonValue));
    }

    /**
     * Retrieves a Page resource.
     * Retrieves a Page resource.
     */
    async apiPagesUrlKeyGet(requestParameters: ApiPagesUrlKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageJsonld> {
        const response = await this.apiPagesUrlKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
