<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * One student's score for one course on one rated section.
 *
 * The unique index on (creator, course, category) is the point of the table: a rating is one
 * replaceable value per person per axis, not a log. Posting again updates that row, and the
 * index is what guarantees it even if two requests race.
 *
 * Cascades on delete because a score is meaningless without the course, section or person it
 * belongs to - there is nothing to keep once any of the three is gone.
 */
final class Version20260826112324 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add course_rating';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE course_rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, value SMALLINT NOT NULL, academic_year VARCHAR(11) NOT NULL, creator_id INT NOT NULL, course_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_76B1E76F61220EA6 ON course_rating (creator_id)');
        $this->addSql('CREATE INDEX IDX_76B1E76F591CC992 ON course_rating (course_id)');
        $this->addSql('CREATE INDEX IDX_76B1E76F12469DE2 ON course_rating (category_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_rating_per_user_course_category ON course_rating (creator_id, course_id, category_id)');
        $this->addSql('ALTER TABLE course_rating ADD CONSTRAINT FK_76B1E76F61220EA6 FOREIGN KEY (creator_id) REFERENCES burgieclan_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course_rating ADD CONSTRAINT FK_76B1E76F591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course_rating ADD CONSTRAINT FK_76B1E76F12469DE2 FOREIGN KEY (category_id) REFERENCES comment_category (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE course_rating DROP CONSTRAINT FK_76B1E76F61220EA6');
        $this->addSql('ALTER TABLE course_rating DROP CONSTRAINT FK_76B1E76F591CC992');
        $this->addSql('ALTER TABLE course_rating DROP CONSTRAINT FK_76B1E76F12469DE2');
        $this->addSql('DROP TABLE course_rating');
    }
}
