<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Exam reconstructions (phase 2d): images uploaded into a reconstruction. The files themselves
 * live in the exam_images.storage filesystem; the document holds their URL.
 */
final class Version20261003121841 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Images in exam reconstructions';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exam_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uuid UUID NOT NULL, file_name VARCHAR(64) NOT NULL, mime_type VARCHAR(32) NOT NULL, size INT NOT NULL, width INT NOT NULL, height INT NOT NULL, removed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, exam_id INT NOT NULL, uploader_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_97D802EFD17F50A6 ON exam_image (uuid)');
        $this->addSql('CREATE INDEX IDX_97D802EF578D5E91 ON exam_image (exam_id)');
        $this->addSql('CREATE INDEX IDX_97D802EF16678C77 ON exam_image (uploader_id)');
        $this->addSql('ALTER TABLE exam_image ADD CONSTRAINT FK_97D802EF578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_image ADD CONSTRAINT FK_97D802EF16678C77 FOREIGN KEY (uploader_id) REFERENCES burgieclan_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exam_image DROP CONSTRAINT FK_97D802EF578D5E91');
        $this->addSql('ALTER TABLE exam_image DROP CONSTRAINT FK_97D802EF16678C77');
        $this->addSql('DROP TABLE exam_image');
    }
}
