<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260829185749 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Track unique users and click counts for the Old Burgieclan header link';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE legacy_site_click (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, click_count INT DEFAULT 1 NOT NULL, last_clicked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D85DE4913448C309 ON legacy_site_click (last_clicked_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_legacy_site_click_user ON legacy_site_click (user_id)');
        $this->addSql('ALTER TABLE legacy_site_click ADD CONSTRAINT FK_D85DE491A76ED395 FOREIGN KEY (user_id) REFERENCES burgieclan_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE legacy_site_click DROP CONSTRAINT FK_D85DE491A76ED395');
        $this->addSql('DROP TABLE legacy_site_click');
    }
}
