<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260929171115 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Stored state of live, collaboratively edited documents (collab server)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE collab_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(100) NOT NULL, state BYTEA NOT NULL, content JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_collab_document_name ON collab_document (name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE collab_document');
    }
}
