<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Exam reconstructions (phase 2a): the questions of each exam as rows, copied from its live
 * document on every store (ExamQuestionSync). Existing exams get theirs on their next store, or
 * right away with `bin/console app:exam-questions:sync`.
 */
final class Version20260930180418 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The questions of exam reconstructions as rows';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exam_question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uid VARCHAR(64) NOT NULL, position INT NOT NULL, text TEXT NOT NULL, sittings JSON NOT NULL, removed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, exam_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F593067D578D5E91 ON exam_question (exam_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_exam_question_exam_uid ON exam_question (exam_id, uid)');
        $this->addSql('ALTER TABLE exam_question ADD CONSTRAINT FK_F593067D578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exam_question DROP CONSTRAINT FK_F593067D578D5E91');
        $this->addSql('DROP TABLE exam_question');
    }
}
