<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Exam reconstructions (phase 1): the exam table, the revision history of live documents, and on
 * collab_document the non-editor fields and who changed it since its last revision.
 */
final class Version20260929195111 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Exam reconstructions and the revision history of live documents';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE collab_document_revision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, state BYTEA NOT NULL, content JSON DEFAULT NULL, fields JSON DEFAULT NULL, contributors JSON NOT NULL, note VARCHAR(255) DEFAULT NULL, document_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BDAC02A9C33F7837 ON collab_document_revision (document_id)');
        $this->addSql('CREATE INDEX idx_collab_document_revision_document_created ON collab_document_revision (document_id, created_at)');
        $this->addSql('CREATE TABLE exam (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, academic_year VARCHAR(11) NOT NULL, period VARCHAR(16) NOT NULL, editable_until TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, creator_id INT DEFAULT NULL, course_id INT NOT NULL, copied_from_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_38BBA6C661220EA6 ON exam (creator_id)');
        $this->addSql('CREATE INDEX IDX_38BBA6C6591CC992 ON exam (course_id)');
        $this->addSql('CREATE INDEX IDX_38BBA6C658B20D94 ON exam (copied_from_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_exam_course_year_period ON exam (course_id, academic_year, period)');
        $this->addSql('ALTER TABLE collab_document_revision ADD CONSTRAINT FK_BDAC02A9C33F7837 FOREIGN KEY (document_id) REFERENCES collab_document (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam ADD CONSTRAINT FK_38BBA6C661220EA6 FOREIGN KEY (creator_id) REFERENCES burgieclan_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam ADD CONSTRAINT FK_38BBA6C6591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam ADD CONSTRAINT FK_38BBA6C658B20D94 FOREIGN KEY (copied_from_id) REFERENCES exam (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE collab_document ADD fields JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE collab_document ADD pending_contributors JSON DEFAULT \'[]\' NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE collab_document_revision DROP CONSTRAINT FK_BDAC02A9C33F7837');
        $this->addSql('ALTER TABLE exam DROP CONSTRAINT FK_38BBA6C661220EA6');
        $this->addSql('ALTER TABLE exam DROP CONSTRAINT FK_38BBA6C6591CC992');
        $this->addSql('ALTER TABLE exam DROP CONSTRAINT FK_38BBA6C658B20D94');
        $this->addSql('DROP TABLE collab_document_revision');
        $this->addSql('DROP TABLE exam');
        $this->addSql('ALTER TABLE collab_document DROP fields');
        $this->addSql('ALTER TABLE collab_document DROP pending_contributors');
    }
}
