<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Add faq_question: the admin inbox for questions asked from the FAQ page.
 *
 * Replaces the mailto: link that used to sit under the FAQ, so questions land in the admin
 * instead of in a mailbox. author_id is ON DELETE SET NULL on purpose — a question stays worth
 * answering publicly after the account that asked it is gone.
 */
final class Version20260813120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add faq_question table for FAQ questions submitted from the frontend';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            <<<'SQL'
            CREATE TABLE faq_question (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                question TEXT NOT NULL,
                locale VARCHAR(2) NOT NULL,
                author_id INT DEFAULT NULL,
                status VARCHAR(20) NOT NULL,
                PRIMARY KEY (id)
            )
        SQL
        );
        $this->addSql('CREATE INDEX IDX_faq_question_author ON faq_question (author_id)');
        // The badge in the admin menu counts new questions on every page load.
        $this->addSql('CREATE INDEX IDX_faq_question_status ON faq_question (status)');
        $this->addSql(
            <<<'SQL'
            ALTER TABLE faq_question
                ADD CONSTRAINT FK_faq_question_author
                FOREIGN KEY (author_id) REFERENCES burgieclan_user (id)
                ON DELETE SET NULL
                NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE faq_question DROP CONSTRAINT IF EXISTS FK_faq_question_author');
        $this->addSql('DROP TABLE IF EXISTS faq_question');
    }
}
