<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Doctrine\Migrations\Exception\IrreversibleMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260411182132 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        // Drop existing sequences to avoid duplicates
        $this->addSql('DROP SEQUENCE IF EXISTS announcement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS burgieclan_user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS comment_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS course_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS course_comment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS course_comment_vote_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS document_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS document_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS document_comment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS document_comment_vote_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS document_vote_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS module_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS page_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS program_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS quick_link_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS refresh_tokens_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS tag_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS user_document_view_id_seq CASCADE');

        // Add new GENERATED BY DEFAULT AS IDENTITY columns
        $this->addSql('ALTER TABLE announcement ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN announcement.create_date IS \'\'');
        $this->addSql('ALTER TABLE burgieclan_user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE comment_category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE course ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE course_comment ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN course_comment.create_date IS \'\'');
        $this->addSql('ALTER TABLE course_comment_vote ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN course_comment_vote.create_date IS \'\'');
        $this->addSql('ALTER TABLE document ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN document.create_date IS \'\'');
        $this->addSql('ALTER TABLE document_category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE document_comment ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN document_comment.create_date IS \'\'');
        $this->addSql('ALTER TABLE document_comment_vote ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN document_comment_vote.create_date IS \'\'');
        $this->addSql('ALTER TABLE document_vote ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN document_vote.create_date IS \'\'');
        $this->addSql('ALTER TABLE module ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE page ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE program ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE quick_link ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE refresh_tokens ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE tag ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE user_document_view ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');

        // Reset sequences to start after the current max ID
        $this->addSql('SELECT setval(\'announcement_id_seq\', COALESCE((SELECT MAX(id) FROM announcement), 1))');
        $this->addSql('SELECT setval(\'burgieclan_user_id_seq\', COALESCE((SELECT MAX(id) FROM burgieclan_user), 1))');
        $this->addSql('SELECT setval(\'comment_category_id_seq\', COALESCE((SELECT MAX(id) FROM comment_category), 1))');
        $this->addSql('SELECT setval(\'course_id_seq\', COALESCE((SELECT MAX(id) FROM course), 1))');
        $this->addSql('SELECT setval(\'course_comment_id_seq\', COALESCE((SELECT MAX(id) FROM course_comment), 1))');
        $this->addSql('SELECT setval(\'course_comment_vote_id_seq\', COALESCE((SELECT MAX(id) FROM course_comment_vote), 1))');
        $this->addSql('SELECT setval(\'document_id_seq\', COALESCE((SELECT MAX(id) FROM document), 1))');
        $this->addSql('SELECT setval(\'document_category_id_seq\', COALESCE((SELECT MAX(id) FROM document_category), 1))');
        $this->addSql('SELECT setval(\'document_comment_id_seq\', COALESCE((SELECT MAX(id) FROM document_comment), 1))');
        $this->addSql('SELECT setval(\'document_comment_vote_id_seq\', COALESCE((SELECT MAX(id) FROM document_comment_vote), 1))');
        $this->addSql('SELECT setval(\'document_vote_id_seq\', COALESCE((SELECT MAX(id) FROM document_vote), 1))');
        $this->addSql('SELECT setval(\'module_id_seq\', COALESCE((SELECT MAX(id) FROM module), 1))');
        $this->addSql('SELECT setval(\'page_id_seq\', COALESCE((SELECT MAX(id) FROM page), 1))');
        $this->addSql('SELECT setval(\'program_id_seq\', COALESCE((SELECT MAX(id) FROM program), 1))');
        $this->addSql('SELECT setval(\'quick_link_id_seq\', COALESCE((SELECT MAX(id) FROM quick_link), 1))');
        $this->addSql('SELECT setval(\'refresh_tokens_id_seq\', COALESCE((SELECT MAX(id) FROM refresh_tokens), 1))');
        $this->addSql('SELECT setval(\'tag_id_seq\', COALESCE((SELECT MAX(id) FROM tag), 1))');
        $this->addSql('SELECT setval(\'user_document_view_id_seq\', COALESCE((SELECT MAX(id) FROM user_document_view), 1))');
    }

    public function down(Schema $schema): void
    {
        throw new IrreversibleMigration('This migration is irreversible.');
    }
}
