<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Exam reconstructions (phase 2b): comments on exam questions, and "Ik had deze ook".
 */
final class Version20261002214438 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Comments and confirmations on exam questions';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exam_question_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, content TEXT NOT NULL, anonymous BOOLEAN NOT NULL, creator_id INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AF9FB9AA61220EA6 ON exam_question_comment (creator_id)');
        $this->addSql('CREATE INDEX IDX_AF9FB9AA1E27F6BF ON exam_question_comment (question_id)');
        $this->addSql('CREATE INDEX idx_exam_question_comment_question_created ON exam_question_comment (question_id, created_at)');
        $this->addSql('CREATE TABLE exam_question_confirmation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, creator_id INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B613190761220EA6 ON exam_question_confirmation (creator_id)');
        $this->addSql('CREATE INDEX IDX_B61319071E27F6BF ON exam_question_confirmation (question_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_exam_question_confirmation_creator_question ON exam_question_confirmation (creator_id, question_id)');
        $this->addSql('ALTER TABLE exam_question_comment ADD CONSTRAINT FK_AF9FB9AA61220EA6 FOREIGN KEY (creator_id) REFERENCES burgieclan_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_question_comment ADD CONSTRAINT FK_AF9FB9AA1E27F6BF FOREIGN KEY (question_id) REFERENCES exam_question (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_question_confirmation ADD CONSTRAINT FK_B613190761220EA6 FOREIGN KEY (creator_id) REFERENCES burgieclan_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_question_confirmation ADD CONSTRAINT FK_B61319071E27F6BF FOREIGN KEY (question_id) REFERENCES exam_question (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exam_question_comment DROP CONSTRAINT FK_AF9FB9AA61220EA6');
        $this->addSql('ALTER TABLE exam_question_comment DROP CONSTRAINT FK_AF9FB9AA1E27F6BF');
        $this->addSql('ALTER TABLE exam_question_confirmation DROP CONSTRAINT FK_B613190761220EA6');
        $this->addSql('ALTER TABLE exam_question_confirmation DROP CONSTRAINT FK_B61319071E27F6BF');
        $this->addSql('DROP TABLE exam_question_comment');
        $this->addSql('DROP TABLE exam_question_confirmation');
    }
}
