/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAnnouncementsGetCollection200ResponseHydraView
 */
export interface ApiAnnouncementsGetCollection200ResponseHydraView {
    /**
     * 
     * @type {any}
     * @memberof ApiAnnouncementsGetCollection200ResponseHydraView
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiAnnouncementsGetCollection200ResponseHydraView
     */
    type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiAnnouncementsGetCollection200ResponseHydraView
     */
    hydrafirst?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiAnnouncementsGetCollection200ResponseHydraView
     */
    hydralast?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiAnnouncementsGetCollection200ResponseHydraView
     */
    hydraprevious?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiAnnouncementsGetCollection200ResponseHydraView
     */
    hydranext?: any | null;
}

/**
 * Check if a given object implements the ApiAnnouncementsGetCollection200ResponseHydraView interface.
 */
export function instanceOfApiAnnouncementsGetCollection200ResponseHydraView(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiAnnouncementsGetCollection200ResponseHydraViewFromJSON(json: any): ApiAnnouncementsGetCollection200ResponseHydraView {
    return ApiAnnouncementsGetCollection200ResponseHydraViewFromJSONTyped(json, false);
}

export function ApiAnnouncementsGetCollection200ResponseHydraViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAnnouncementsGetCollection200ResponseHydraView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'hydrafirst': !exists(json, 'hydra:first') ? undefined : json['hydra:first'],
        'hydralast': !exists(json, 'hydra:last') ? undefined : json['hydra:last'],
        'hydraprevious': !exists(json, 'hydra:previous') ? undefined : json['hydra:previous'],
        'hydranext': !exists(json, 'hydra:next') ? undefined : json['hydra:next'],
    };
}

export function ApiAnnouncementsGetCollection200ResponseHydraViewToJSON(value?: ApiAnnouncementsGetCollection200ResponseHydraView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@id': value.id,
        '@type': value.type,
        'hydra:first': value.hydrafirst,
        'hydra:last': value.hydralast,
        'hydra:previous': value.hydraprevious,
        'hydra:next': value.hydranext,
    };
}

