/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAnnouncementsGetCollection200ResponseHydraSearch
 */
export interface ApiAnnouncementsGetCollection200ResponseHydraSearch {
    /**
     * 
     * @type {any}
     * @memberof ApiAnnouncementsGetCollection200ResponseHydraSearch
     */
    type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiAnnouncementsGetCollection200ResponseHydraSearch
     */
    hydratemplate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiAnnouncementsGetCollection200ResponseHydraSearch
     */
    hydravariableRepresentation?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiAnnouncementsGetCollection200ResponseHydraSearch
     */
    hydramapping?: any | null;
}

/**
 * Check if a given object implements the ApiAnnouncementsGetCollection200ResponseHydraSearch interface.
 */
export function instanceOfApiAnnouncementsGetCollection200ResponseHydraSearch(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiAnnouncementsGetCollection200ResponseHydraSearchFromJSON(json: any): ApiAnnouncementsGetCollection200ResponseHydraSearch {
    return ApiAnnouncementsGetCollection200ResponseHydraSearchFromJSONTyped(json, false);
}

export function ApiAnnouncementsGetCollection200ResponseHydraSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAnnouncementsGetCollection200ResponseHydraSearch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'hydratemplate': !exists(json, 'hydra:template') ? undefined : json['hydra:template'],
        'hydravariableRepresentation': !exists(json, 'hydra:variableRepresentation') ? undefined : json['hydra:variableRepresentation'],
        'hydramapping': !exists(json, 'hydra:mapping') ? undefined : json['hydra:mapping'],
    };
}

export function ApiAnnouncementsGetCollection200ResponseHydraSearchToJSON(value?: ApiAnnouncementsGetCollection200ResponseHydraSearch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@type': value.type,
        'hydra:template': value.hydratemplate,
        'hydra:variableRepresentation': value.hydravariableRepresentation,
        'hydra:mapping': value.hydramapping,
    };
}

