/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiAnnouncementsGetCollection200ResponseHydraSearch } from './ApiAnnouncementsGetCollection200ResponseHydraSearch';
import {
    ApiAnnouncementsGetCollection200ResponseHydraSearchFromJSON,
    ApiAnnouncementsGetCollection200ResponseHydraSearchFromJSONTyped,
    ApiAnnouncementsGetCollection200ResponseHydraSearchToJSON,
} from './ApiAnnouncementsGetCollection200ResponseHydraSearch';
import type { ApiAnnouncementsGetCollection200ResponseHydraView } from './ApiAnnouncementsGetCollection200ResponseHydraView';
import {
    ApiAnnouncementsGetCollection200ResponseHydraViewFromJSON,
    ApiAnnouncementsGetCollection200ResponseHydraViewFromJSONTyped,
    ApiAnnouncementsGetCollection200ResponseHydraViewToJSON,
} from './ApiAnnouncementsGetCollection200ResponseHydraView';

/**
 * 
 * @export
 * @interface ApiDocumentsGetCollection200Response
 */
export interface ApiDocumentsGetCollection200Response {
    /**
     * 
     * @type {any}
     * @memberof ApiDocumentsGetCollection200Response
     */
    hydramember: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiDocumentsGetCollection200Response
     */
    hydratotalItems?: any | null;
    /**
     * 
     * @type {ApiAnnouncementsGetCollection200ResponseHydraView}
     * @memberof ApiDocumentsGetCollection200Response
     */
    hydraview?: ApiAnnouncementsGetCollection200ResponseHydraView;
    /**
     * 
     * @type {ApiAnnouncementsGetCollection200ResponseHydraSearch}
     * @memberof ApiDocumentsGetCollection200Response
     */
    hydrasearch?: ApiAnnouncementsGetCollection200ResponseHydraSearch;
}

/**
 * Check if a given object implements the ApiDocumentsGetCollection200Response interface.
 */
export function instanceOfApiDocumentsGetCollection200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hydramember" in value;

    return isInstance;
}

export function ApiDocumentsGetCollection200ResponseFromJSON(json: any): ApiDocumentsGetCollection200Response {
    return ApiDocumentsGetCollection200ResponseFromJSONTyped(json, false);
}

export function ApiDocumentsGetCollection200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDocumentsGetCollection200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hydramember': json['hydra:member'],
        'hydratotalItems': !exists(json, 'hydra:totalItems') ? undefined : json['hydra:totalItems'],
        'hydraview': !exists(json, 'hydra:view') ? undefined : ApiAnnouncementsGetCollection200ResponseHydraViewFromJSON(json['hydra:view']),
        'hydrasearch': !exists(json, 'hydra:search') ? undefined : ApiAnnouncementsGetCollection200ResponseHydraSearchFromJSON(json['hydra:search']),
    };
}

export function ApiDocumentsGetCollection200ResponseToJSON(value?: ApiDocumentsGetCollection200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hydra:member': value.hydramember,
        'hydra:totalItems': value.hydratotalItems,
        'hydra:view': ApiAnnouncementsGetCollection200ResponseHydraViewToJSON(value.hydraview),
        'hydra:search': ApiAnnouncementsGetCollection200ResponseHydraSearchToJSON(value.hydrasearch),
    };
}

