/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentCategoryJsonld
 */
export interface CommentCategoryJsonld {
    /**
     * 
     * @type {any}
     * @memberof CommentCategoryJsonld
     */
    readonly id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CommentCategoryJsonld
     */
    readonly type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CommentCategoryJsonld
     */
    readonly context?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CommentCategoryJsonld
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof CommentCategoryJsonld
     */
    description?: any | null;
}

/**
 * Check if a given object implements the CommentCategoryJsonld interface.
 */
export function instanceOfCommentCategoryJsonld(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CommentCategoryJsonldFromJSON(json: any): CommentCategoryJsonld {
    return CommentCategoryJsonldFromJSONTyped(json, false);
}

export function CommentCategoryJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentCategoryJsonld {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'context': !exists(json, '@context') ? undefined : json['@context'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function CommentCategoryJsonldToJSON(value?: CommentCategoryJsonld | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}

