/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseComment
 */
export interface CourseComment {
    /**
     * 
     * @type {any}
     * @memberof CourseComment
     */
    course?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CourseComment
     */
    category?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CourseComment
     */
    content: any | null;
    /**
     * 
     * @type {any}
     * @memberof CourseComment
     */
    anonymous?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CourseComment
     */
    readonly creator?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CourseComment
     */
    readonly createdAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CourseComment
     */
    readonly updatedAt?: any | null;
}

/**
 * Check if a given object implements the CourseComment interface.
 */
export function instanceOfCourseComment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function CourseCommentFromJSON(json: any): CourseComment {
    return CourseCommentFromJSONTyped(json, false);
}

export function CourseCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseComment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'course': !exists(json, 'course') ? undefined : json['course'],
        'category': !exists(json, 'category') ? undefined : json['category'],
        'content': json['content'],
        'anonymous': !exists(json, 'anonymous') ? undefined : json['anonymous'],
        'creator': !exists(json, 'creator') ? undefined : json['creator'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function CourseCommentToJSON(value?: CourseComment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'course': value.course,
        'category': value.category,
        'content': value.content,
        'anonymous': value.anonymous,
    };
}

