/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentCommentJsonld
 */
export interface DocumentCommentJsonld {
    /**
     * 
     * @type {any}
     * @memberof DocumentCommentJsonld
     */
    readonly context?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCommentJsonld
     */
    readonly id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCommentJsonld
     */
    readonly type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCommentJsonld
     */
    document?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCommentJsonld
     */
    content: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCommentJsonld
     */
    anonymous?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCommentJsonld
     */
    readonly creator?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCommentJsonld
     */
    readonly createdAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCommentJsonld
     */
    readonly updatedAt?: any | null;
}

/**
 * Check if a given object implements the DocumentCommentJsonld interface.
 */
export function instanceOfDocumentCommentJsonld(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function DocumentCommentJsonldFromJSON(json: any): DocumentCommentJsonld {
    return DocumentCommentJsonldFromJSONTyped(json, false);
}

export function DocumentCommentJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentCommentJsonld {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'context': !exists(json, '@context') ? undefined : json['@context'],
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'document': !exists(json, 'document') ? undefined : json['document'],
        'content': json['content'],
        'anonymous': !exists(json, 'anonymous') ? undefined : json['anonymous'],
        'creator': !exists(json, 'creator') ? undefined : json['creator'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function DocumentCommentJsonldToJSON(value?: DocumentCommentJsonld | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'document': value.document,
        'content': value.content,
        'anonymous': value.anonymous,
    };
}

