/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentComment
 */
export interface DocumentComment {
    /**
     * 
     * @type {any}
     * @memberof DocumentComment
     */
    document?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentComment
     */
    content: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentComment
     */
    anonymous?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentComment
     */
    readonly creator?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentComment
     */
    readonly createdAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentComment
     */
    readonly updatedAt?: any | null;
}

/**
 * Check if a given object implements the DocumentComment interface.
 */
export function instanceOfDocumentComment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function DocumentCommentFromJSON(json: any): DocumentComment {
    return DocumentCommentFromJSONTyped(json, false);
}

export function DocumentCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentComment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'document': !exists(json, 'document') ? undefined : json['document'],
        'content': json['content'],
        'anonymous': !exists(json, 'anonymous') ? undefined : json['anonymous'],
        'creator': !exists(json, 'creator') ? undefined : json['creator'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function DocumentCommentToJSON(value?: DocumentComment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'document': value.document,
        'content': value.content,
        'anonymous': value.anonymous,
    };
}

