/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentJsonld
 */
export interface DocumentJsonld {
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    readonly context?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    readonly id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    readonly type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    course?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    category?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    readonly underReview?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    contentUrl?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    file?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    readonly creator?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    readonly createdAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentJsonld
     */
    readonly updatedAt?: any | null;
}

/**
 * Check if a given object implements the DocumentJsonld interface.
 */
export function instanceOfDocumentJsonld(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function DocumentJsonldFromJSON(json: any): DocumentJsonld {
    return DocumentJsonldFromJSONTyped(json, false);
}

export function DocumentJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentJsonld {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'context': !exists(json, '@context') ? undefined : json['@context'],
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'name': json['name'],
        'course': !exists(json, 'course') ? undefined : json['course'],
        'category': !exists(json, 'category') ? undefined : json['category'],
        'underReview': !exists(json, 'under_review') ? undefined : json['under_review'],
        'contentUrl': !exists(json, 'contentUrl') ? undefined : json['contentUrl'],
        'file': !exists(json, 'file') ? undefined : json['file'],
        'creator': !exists(json, 'creator') ? undefined : json['creator'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function DocumentJsonldToJSON(value?: DocumentJsonld | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'course': value.course,
        'category': value.category,
        'contentUrl': value.contentUrl,
        'file': value.file,
    };
}

