/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentCategoryJsonld
 */
export interface DocumentCategoryJsonld {
    /**
     * 
     * @type {any}
     * @memberof DocumentCategoryJsonld
     */
    readonly id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCategoryJsonld
     */
    readonly type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCategoryJsonld
     */
    readonly context?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCategoryJsonld
     */
    name: any | null;
}

/**
 * Check if a given object implements the DocumentCategoryJsonld interface.
 */
export function instanceOfDocumentCategoryJsonld(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function DocumentCategoryJsonldFromJSON(json: any): DocumentCategoryJsonld {
    return DocumentCategoryJsonldFromJSONTyped(json, false);
}

export function DocumentCategoryJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentCategoryJsonld {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'context': !exists(json, '@context') ? undefined : json['@context'],
        'name': json['name'],
    };
}

export function DocumentCategoryJsonldToJSON(value?: DocumentCategoryJsonld | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

