/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LitusAuthenticationJsonld
 */
export interface LitusAuthenticationJsonld {
    /**
     * 
     * @type {any}
     * @memberof LitusAuthenticationJsonld
     */
    readonly context?: any | null;
    /**
     * 
     * @type {any}
     * @memberof LitusAuthenticationJsonld
     */
    readonly id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof LitusAuthenticationJsonld
     */
    readonly type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof LitusAuthenticationJsonld
     */
    accessToken?: any | null;
}

/**
 * Check if a given object implements the LitusAuthenticationJsonld interface.
 */
export function instanceOfLitusAuthenticationJsonld(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LitusAuthenticationJsonldFromJSON(json: any): LitusAuthenticationJsonld {
    return LitusAuthenticationJsonldFromJSONTyped(json, false);
}

export function LitusAuthenticationJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): LitusAuthenticationJsonld {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'context': !exists(json, '@context') ? undefined : json['@context'],
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
    };
}

export function LitusAuthenticationJsonldToJSON(value?: LitusAuthenticationJsonld | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
    };
}

