/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginCheckPost200Response
 */
export interface LoginCheckPost200Response {
    /**
     * 
     * @type {any}
     * @memberof LoginCheckPost200Response
     */
    readonly token: any | null;
}

/**
 * Check if a given object implements the LoginCheckPost200Response interface.
 */
export function instanceOfLoginCheckPost200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function LoginCheckPost200ResponseFromJSON(json: any): LoginCheckPost200Response {
    return LoginCheckPost200ResponseFromJSONTyped(json, false);
}

export function LoginCheckPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginCheckPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function LoginCheckPost200ResponseToJSON(value?: LoginCheckPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

