/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginCheckPostRequest
 */
export interface LoginCheckPostRequest {
    /**
     * 
     * @type {any}
     * @memberof LoginCheckPostRequest
     */
    username: any | null;
    /**
     * 
     * @type {any}
     * @memberof LoginCheckPostRequest
     */
    password: any | null;
}

/**
 * Check if a given object implements the LoginCheckPostRequest interface.
 */
export function instanceOfLoginCheckPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function LoginCheckPostRequestFromJSON(json: any): LoginCheckPostRequest {
    return LoginCheckPostRequestFromJSONTyped(json, false);
}

export function LoginCheckPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginCheckPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function LoginCheckPostRequestToJSON(value?: LoginCheckPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

