/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModuleJsonld
 */
export interface ModuleJsonld {
    /**
     * 
     * @type {any}
     * @memberof ModuleJsonld
     */
    readonly id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModuleJsonld
     */
    readonly type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModuleJsonld
     */
    readonly context?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModuleJsonld
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModuleJsonld
     */
    courses?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModuleJsonld
     */
    modules?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModuleJsonld
     */
    program?: any | null;
}

/**
 * Check if a given object implements the ModuleJsonld interface.
 */
export function instanceOfModuleJsonld(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ModuleJsonldFromJSON(json: any): ModuleJsonld {
    return ModuleJsonldFromJSONTyped(json, false);
}

export function ModuleJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModuleJsonld {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'context': !exists(json, '@context') ? undefined : json['@context'],
        'name': json['name'],
        'courses': !exists(json, 'courses') ? undefined : json['courses'],
        'modules': !exists(json, 'modules') ? undefined : json['modules'],
        'program': !exists(json, 'program') ? undefined : json['program'],
    };
}

export function ModuleJsonldToJSON(value?: ModuleJsonld | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'courses': value.courses,
        'modules': value.modules,
        'program': value.program,
    };
}

