/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageJsonld
 */
export interface PageJsonld {
    /**
     * 
     * @type {any}
     * @memberof PageJsonld
     */
    readonly context?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PageJsonld
     */
    readonly id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PageJsonld
     */
    readonly type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PageJsonld
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof PageJsonld
     */
    content: any | null;
    /**
     * 
     * @type {any}
     * @memberof PageJsonld
     */
    publicAvailable?: any | null;
}

/**
 * Check if a given object implements the PageJsonld interface.
 */
export function instanceOfPageJsonld(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function PageJsonldFromJSON(json: any): PageJsonld {
    return PageJsonldFromJSONTyped(json, false);
}

export function PageJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageJsonld {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'context': !exists(json, '@context') ? undefined : json['@context'],
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'name': json['name'],
        'content': json['content'],
        'publicAvailable': !exists(json, 'publicAvailable') ? undefined : json['publicAvailable'],
    };
}

export function PageJsonldToJSON(value?: PageJsonld | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'content': value.content,
        'publicAvailable': value.publicAvailable,
    };
}

