/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserFavorites
 */
export interface UserFavorites {
    /**
     * 
     * @type {any}
     * @memberof UserFavorites
     */
    readonly fullName: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavorites
     */
    readonly username: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavorites
     */
    readonly email?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavorites
     */
    favoriteCourses?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavorites
     */
    favoriteModules?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavorites
     */
    favoritePrograms?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavorites
     */
    favoriteDocuments?: any | null;
}

/**
 * Check if a given object implements the UserFavorites interface.
 */
export function instanceOfUserFavorites(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fullName" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function UserFavoritesFromJSON(json: any): UserFavorites {
    return UserFavoritesFromJSONTyped(json, false);
}

export function UserFavoritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFavorites {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': json['fullName'],
        'username': json['username'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'favoriteCourses': !exists(json, 'favoriteCourses') ? undefined : json['favoriteCourses'],
        'favoriteModules': !exists(json, 'favoriteModules') ? undefined : json['favoriteModules'],
        'favoritePrograms': !exists(json, 'favoritePrograms') ? undefined : json['favoritePrograms'],
        'favoriteDocuments': !exists(json, 'favoriteDocuments') ? undefined : json['favoriteDocuments'],
    };
}

export function UserFavoritesToJSON(value?: UserFavorites | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'favoriteCourses': value.favoriteCourses,
        'favoriteModules': value.favoriteModules,
        'favoritePrograms': value.favoritePrograms,
        'favoriteDocuments': value.favoriteDocuments,
    };
}

