/* tslint:disable */
/* eslint-disable */
/**
 * Burgieclan API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserFavoritesJsonldUserFavorites
 */
export interface UserFavoritesJsonldUserFavorites {
    /**
     * 
     * @type {any}
     * @memberof UserFavoritesJsonldUserFavorites
     */
    readonly context?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavoritesJsonldUserFavorites
     */
    readonly id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavoritesJsonldUserFavorites
     */
    readonly type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavoritesJsonldUserFavorites
     */
    favoriteCourses?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavoritesJsonldUserFavorites
     */
    favoriteModules?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavoritesJsonldUserFavorites
     */
    favoritePrograms?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserFavoritesJsonldUserFavorites
     */
    favoriteDocuments?: any | null;
}

/**
 * Check if a given object implements the UserFavoritesJsonldUserFavorites interface.
 */
export function instanceOfUserFavoritesJsonldUserFavorites(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserFavoritesJsonldUserFavoritesFromJSON(json: any): UserFavoritesJsonldUserFavorites {
    return UserFavoritesJsonldUserFavoritesFromJSONTyped(json, false);
}

export function UserFavoritesJsonldUserFavoritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFavoritesJsonldUserFavorites {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'context': !exists(json, '@context') ? undefined : json['@context'],
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'favoriteCourses': !exists(json, 'favoriteCourses') ? undefined : json['favoriteCourses'],
        'favoriteModules': !exists(json, 'favoriteModules') ? undefined : json['favoriteModules'],
        'favoritePrograms': !exists(json, 'favoritePrograms') ? undefined : json['favoritePrograms'],
        'favoriteDocuments': !exists(json, 'favoriteDocuments') ? undefined : json['favoriteDocuments'],
    };
}

export function UserFavoritesJsonldUserFavoritesToJSON(value?: UserFavoritesJsonldUserFavorites | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'favoriteCourses': value.favoriteCourses,
        'favoriteModules': value.favoriteModules,
        'favoritePrograms': value.favoritePrograms,
        'favoriteDocuments': value.favoriteDocuments,
    };
}

