name: PHP Code Sniffer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Cache Composer dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: backend/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: "8.4"

      - name: Install dependencies
        run: composer install

      - name: Run PHP Code Sniffer
        run: vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1

      - name: Print local fix instructions
        if: failure()
        run: |
          echo "To fix PHP CodeSniffer errors locally, run:"
          echo "  vendor/bin/phpcbf"
